---
global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format: ["prometheus"]
    scheme: https
    tls_config:
      insecure_skip_verify: true
      ca_file: /certs/cert.pem
    static_configs:
      - targets:
          - client-1:443
        labels:
          service: vault
          env: dev
