---
stages:
  - lint

image: ubuntu:18.04

lint_yml:
  stage: lint
  image: sdesbure/yamllint
  script:
    - yamllint ./ -c yamllint.yml --strict

lint_shell:
  stage: lint
  image: koalaman/shellcheck-alpine:v0.5.0
  script:
    - find ./ -name '*.sh' | xargs shellcheck
