---
stages:
  - linters

image: ubuntu:18.04

lint_yml:
  stage: linters
  image: sdesbure/yamllint
  script:
    - yamllint ./

lint_shell:
  stage: linters
  image: koalaman/shellcheck-alpine:v0.5.0
  script:
    - find ./ -name '*.sh' | xargs shellcheck
