---
version: '2.3'
services:

  # Alpha cluster

  a-node-1:
    container_name: a-node-1
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50M"
        max-file: "2"
    networks:
      default:
        aliases:
          - a-node-1
        ipv4_address: 192.168.4.66
    volumes:
      - "./alpha/configs/consul-node-1.json:/consul/config/server.json:ro"
      - "./alpha/data/a-node-1:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  a-node-2:
    container_name: a-node-2
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50M"
        max-file: "2"
    networks:
      default:
        aliases:
          - a-node-2
        ipv4_address: 192.168.4.67
    volumes:
      - "./alpha/configs/consul-node-2.json:/consul/config/server.json:ro"
      - "./alpha/data/a-node-2:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  a-node-3:
    container_name: a-node-3
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50M"
        max-file: "2"
    networks:
      default:
        aliases:
          - a-node-3
        ipv4_address: 192.168.4.68
    volumes:
      - "./alpha/configs/consul-node-3.json:/consul/config/server.json:ro"
      - "./alpha/data/a-node-3:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  a-agent-1:
    container_name: a-agent-1
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50M"
        max-file: "2"
    networks:
      default:
        aliases:
          - a-agent-1
        ipv4_address: 192.168.4.72
    volumes:
      - "./alpha/configs/consul-agent-1.json:/consul/config/server.json:ro"
      - "./alpha/data/a-agent-1:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  a-vault-node-1:
    image: vault:0.11.0
    container_name: a-vault-node-1
    cap_add:
      - IPC_LOCK
    networks:
      default:
        aliases:
          - a-vault-node-1
        ipv4_address: 192.168.4.74
    volumes:
      - "./alpha/configs/vault-node-1.hcl:/vault/config/config.hcl:ro"
    command: ["vault", "server", "--config=/vault/config/config.hcl"]

  # Beta cluster

  b-node-1:
    container_name: b-node-1
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50M"
        max-file: "2"
    networks:
      default:
        aliases:
          - b-node-1
        ipv4_address: 192.168.4.69
    volumes:
      - "./beta/configs/consul-node-1.json:/consul/config/server.json:ro"
      - "./beta/data/b-node-1:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  b-node-2:
    container_name: b-node-2
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50M"
        max-file: "2"
    networks:
      default:
        aliases:
          - b-node-2
        ipv4_address: 192.168.4.70
    volumes:
      - "./beta/configs/consul-node-2.json:/consul/config/server.json:ro"
      - "./beta/data/b-node-2:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  b-node-3:
    container_name: b-node-3
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50M"
        max-file: "2"
    networks:
      default:
        aliases:
          - b-node-3
        ipv4_address: 192.168.4.71
    volumes:
      - "./beta/configs/consul-node-3.json:/consul/config/server.json:ro"
      - "./beta/data/b-node-3:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  b-agent-1:
    container_name: b-agent-1
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50M"
        max-file: "2"
    networks:
      default:
        aliases:
          - b-agent-1
        ipv4_address: 192.168.4.73
    volumes:
      - "./beta/configs/consul-agent-1.json:/consul/config/server.json:ro"
      - "./beta/data/b-agent-1:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  b-vault-node-1:
    image: vault:0.11.0
    container_name: b-vault-node-1
    cap_add:
      - IPC_LOCK
    networks:
      default:
        aliases:
          - b-vault-node-1
        ipv4_address: 192.168.4.75
    volumes:
      - "./beta/configs/vault-node-1.hcl:/vault/config/config.hcl:ro"
    command: ["vault", "server", "--config=/vault/config/config.hcl"]


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.64/28
