---
version: '2.3'

x-logging-json: &logging-json
  logging:
    driver: json-file
    options:
      max-file: "1"
      max-size: "50M"

x-consul-proto: &consul-proto
  command: ["consul", "agent", "-config-dir", "/consul/config/"]

x-vault-server-proto: &vault-server-proto
  command: ["vault", "server", "--config=/vault/config/config.hcl"]

x-vault-agent-proto: &vault-agent-proto
  command: ["vault", "agent", "--config=/vault/config/config.hcl"]

services:
  vault-server:
    <<: *logging-json
    <<: *vault-server-proto
    image: ${DOCKER_REGISTRY}${REGISTRY_COMMON_STORAGE}vault:${VAULT_VERSION:-1.2.0}
    volumes:
      - "./conf/vault-server.hcl:/vault/config/config.hcl:ro"
    networks:
      default:
        ipv4_address: 172.18.1.21

  vault-agent:
    <<: *logging-json
    <<: *vault-agent-proto
    image: ${DOCKER_REGISTRY}${REGISTRY_COMMON_STORAGE}vault:${VAULT_VERSION:-1.2.0}
    volumes:
      - "./conf/vault-agent.hcl:/vault/config/config.hcl:ro"
    networks:
      default:
        ipv4_address: 172.18.1.20

  consul-agent:
    <<: *logging-json
    <<: *consul-proto
    image: ${DOCKER_REGISTRY}${REGISTRY_COMMON_STORAGE}consul:${CONSUL_AGENT_VERSION:-1.5.3}
    volumes:
      - './conf/consul-agent.hcl:/consul/config/config.hcl:ro'
      - 'consul-agent:/consul/data:rw'
    networks:
      default:
        ipv4_address: 172.18.1.18

  consul-server:
    <<: *logging-json
    <<: *consul-proto
    image: ${DOCKER_REGISTRY}${REGISTRY_COMMON_STORAGE}consul:${CONSUL_SERVER_VERSION:-1.5.3}
    volumes:
      - './conf/consul-server.hcl:/consul/config/config.hcl:ro'
      - 'consul-server:/consul/data:rw'
    networks:
      default:
        ipv4_address: 172.18.1.19

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.16/29

volumes:
  consul-agent:
  consul-server:
