---
version: '2.1'
services:
  vault-simple:
    image: vault:0.11.2
    container_name: dev-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: b4d31592-8e6f-583e-2def-0e0f962da3e9
      VAULT_LOG_LEVEL: debug
    cap_add:
      - IPC_LOCK
    logging:
      driver: json-file
      options:
        labels: env,service,clustered
        env: dev
        max-size: "10M"
        max-file: "2"
    labels:
      env: dev
      service: vault
      clustered: 'false'
    network_mode: host
