---
version: '2.1'
services:
  vault-simple:
    image: vault:1.0.1
    container_name: dev-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 12345
      VAULT_LOG_LEVEL: debug
    cap_add:
      - IPC_LOCK
    logging:
      driver: json-file
      options:
        labels: env,service,clustered
        env: dev
        max-size: "10M"
        max-file: "2"
    labels:
      env: dev
      service: vault
      clustered: 'false'
    network_mode: host
