---
version: '2.3'

x-logging-json: &logging-json
  logging:
    driver: json-file
    options:
      max-file: "1"
      max-size: "50M"

services:
  server:
    <<: *logging-json
    image: ${DOCKER_REGISTRY}${REGISTRY_COMMON_STORAGE}vault:${VAULT_VERSION}
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_TOKEN}
      VAULT_LOG_LEVEL: ${VAULT_LOG_LEVEL}
    cap_add:
      - IPC_LOCK
      - SETFCAP
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    labels:
      env: dev
      service: vault
      clustered: 'false'
    volumes:
      - vault-dev-config:/vault/config:ro
      - vault-dev-data:/vault/file:rw
    command: ["vault", "server", "--config=/vault/config/server.hcl"]
    networks:
      vault-dev-local:
        ipv4_address: 192.168.9.2

volumes:
  vault-dev-config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/conf

  vault-dev-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/data

networks:
  vault-dev-local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.9.0/30
