---
version: '2.3'

x-logging-json: &logging-json
  logging:
    driver: json-file
    options:
      max-file: "1"
      max-size: "50M"

services:
  minio:
    <<: *logging-json
    image: ${DOCKER_REGISTRY}minio/minio:${MINIO_SERVER_VERSION}
    command: ["server", "/data"]
    volumes:
      - './minio_data:/data'
    ports:
      - "0.0.0.0:9000:9000"

#  nginx:
#    <<: *logging-json
#    image: ${DOCKER_REGISTRY}${REGISTRY_COMMON_STORAGE}nginx:${NGINX_VERSION}
#    volumes:
#      - "./configs/nginx/conf.d:/etc/nginx/conf.d:ro"
#      - "./configs/nginx/certs:/etc/nginx/certs:ro"
#      - "./configs/nginx/includes.d:/etc/nginx/includes.d:ro"
#      - "./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
#    ports:
#      - "0.0.0.0:443:443"
#      - "0.0.0.0:80:80"

volumes:
  minio_data:
