---
version: '2.2'
services:
  consul-node-1:
    container_name: consul-cluster-node-1
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: "50M"
    networks:
      default:
        aliases:
          - consul-node-1
        ipv4_address: 192.168.4.2
    volumes:
      - "./configs/consul-server/consul-cluster-node-1.json:/consul/config/server.json:ro"
      - "./data/consul-cluster-node-1:/consul/data:rw"
      - "./consul.snap:/consul.snap:ro"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  consul-node-2:
    container_name: consul-cluster-node-2
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: "50M"
    networks:
      default:
        aliases:
          - consul-node-2
        ipv4_address: 192.168.4.3
    volumes:
      - "./configs/consul-server/consul-cluster-node-2.json:/consul/config/server.json:ro"
      - "./data/consul-cluster-node-2:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  consul-node-3:
    container_name: consul-cluster-node-3
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: "50M"
    networks:
      default:
        aliases:
          - consul-node-3
        ipv4_address: 192.168.4.4
    volumes:
      - "./configs/consul-server/consul-cluster-node-3.json:/consul/config/server.json:ro"
      - "./data/consul-cluster-node-3:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  consul-node-4:
    container_name: consul-cluster-node-4
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: "50M"
    networks:
      default:
        aliases:
          - consul-node-4
        ipv4_address: 192.168.4.9
    volumes:
      - "./configs/consul-server/consul-cluster-node-4.json:/consul/config/server.json:ro"
      - "./data/consul-cluster-node-4:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  consul-node-5:
    container_name: consul-cluster-node-5
    image: consul:1.3.0
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: "50M"
    networks:
      default:
        aliases:
          - consul-node-5
        ipv4_address: 192.168.4.10
    volumes:
      - "./configs/consul-server/consul-cluster-node-5.json:/consul/config/server.json:ro"
      - "./data/consul-cluster-node-5:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  vault-client-1:
    build:
      context: ./client-srv
      args:
        CONSUL_VERSION: 1.3.0
        VAULT_VERSION: 0.11.5
        STATSD_EXPORTER_VERSION: 0.8.0
      network: vaultcluster_default
    image: vault-consul-client:node-1
    container_name: vault-client-1
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: "50M"
    cap_add:
      - IPC_LOCK
    networks:
      default:
        aliases:
          - vault-client-1
        ipv4_address: 192.168.4.6
    volumes:
      - "./configs/consul-client/consul-agent-node-1.json:/consul/config/server.json:ro"
      - "./configs/consul-client/vault-config-node-1.hcl:/vault/config/config.hcl:ro"

  vault-client-2:
    build:
      context: ./client-srv
      args:
        CONSUL_VERSION: 1.3.0
        VAULT_VERSION: 0.11.5
        STATSD_EXPORTER_VERSION: 0.8.0
      network: vaultcluster_default
    image: vault-consul-client:node-2
    container_name: vault-client-2
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: "50M"
    cap_add:
      - IPC_LOCK
    networks:
      default:
        aliases:
          - vault-client-2
        ipv4_address: 192.168.4.7
    volumes:
      - "./configs/consul-client/consul-agent-node-2.json:/consul/config/server.json:ro"
      - "./configs/consul-client/vault-config-node-2.hcl:/vault/config/config.hcl:ro"

  vault-client-3:
    build:
      context: ./client-srv
      args:
        CONSUL_VERSION: 1.3.0
        VAULT_VERSION: 0.11.5
        STATSD_EXPORTER_VERSION: 0.8.0
      network: vaultcluster_default
    image: vault-consul-client:node-3
    container_name: vault-client-3
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: "50M"
    cap_add:
      - IPC_LOCK
    networks:
      default:
        aliases:
          - vault-client-3
        ipv4_address: 192.168.4.8
    volumes:
      - "./configs/consul-client/consul-agent-node-3.json:/consul/config/server.json:ro"
      - "./configs/consul-client/vault-config-node-3.hcl:/vault/config/config.hcl:ro"


  statsd-exporter:
    build:
      context: ./statsd_exporter
      args:
        STATSD_EXPORTER_VERSION: 0.8.0
        ALPINE_VERSION: 3.8
      network: vaultcluster_default
    image: statsd-exporter:0.8.0
    container_name: statsd-exporter
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: "50M"
    networks:
      default:
        aliases:
          - statsd-exporter
        ipv4_address: 192.168.4.11

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/26
