version: '3.2'
services:
  consul-node-1:
    container_name: consul-cluster-node-1
    image: consul:1.2.2
    restart: always
    logging:
      driver: journald
      options:
        tag: consul.node1.prod
    networks:
      default:
        aliases:
          - consul-node-1
        ipv4_address: 192.168.4.2
    volumes:
      - "./configs/consul-server/consul-cluster-node-1.json:/consul/config/server.json:ro"
      - "./data/consul-cluster-node-1:/consul/data:rw"
      - "./consul.snap:/consul.snap:ro"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]
  
  consul-node-2:
    container_name: consul-cluster-node-2
    image: consul:1.2.2
    restart: always
    logging:
      driver: journald
      options:
        tag: consul.node2.prod
    networks:
      default:
        aliases:
          - consul-node-2
        ipv4_address: 192.168.4.3
    volumes:
      - "./configs/consul-server/consul-cluster-node-2.json:/consul/config/server.json:ro"
      - "./data/consul-cluster-node-2:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]
    
  consul-node-3:
    container_name: consul-cluster-node-3
    image: consul:1.2.2
    restart: always
    logging:
      driver: journald
      options:
        tag: consul.node3.prod
    networks:
      default:
        aliases:
          - consul-node-3
        ipv4_address: 192.168.4.4
    volumes:
      - "./configs/consul-server/consul-cluster-node-3.json:/consul/config/server.json:ro"
      - "./data/consul-cluster-node-3:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  consul-node-4:
    container_name: consul-cluster-node-4
    image: consul:1.2.2
    restart: always
    logging:
      driver: journald
      options:
        tag: consul.node4.prod
    networks:
      default:
        aliases:
          - consul-node-3
        ipv4_address: 192.168.4.9
    volumes:
      - "./configs/consul-server/consul-cluster-node-4.json:/consul/config/server.json:ro"
      - "./data/consul-cluster-node-4:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  consul-node-5:
    container_name: consul-cluster-node-5
    image: consul:1.2.2
    restart: always
    logging:
      driver: journald
      options:
        tag: consul.node5.prod
    networks:
      default:
        aliases:
          - consul-node-3
        ipv4_address: 192.168.4.10
    volumes:
      - "./configs/consul-server/consul-cluster-node-5.json:/consul/config/server.json:ro"
      - "./data/consul-cluster-node-5:/consul/data:rw"
    command: ["consul", "agent", "-config-dir", "/consul/config/"]

  vault-client-1:
    build:
      context: ./client-srv
      args:
        CONSUL_VERSION: 1.2.2
        VAULT_VERSION: 0.11.1
    image: vault-consul-client:node-1
    container_name: vault-client-1
    cap_add:
      - IPC_LOCK
    networks:
      default:
        aliases:
          - vault-client-1
        ipv4_address: 192.168.4.6
    volumes:
      - "./configs/consul-client/consul-agent-node-1.json:/consul/config/server.json:ro"
      - "./configs/consul-client/vault-config-node-1.hcl:/vault/config/config.hcl:ro"

  vault-client-2:
    build:
      context: ./client-srv
      args:
        CONSUL_VERSION: 1.2.2
        VAULT_VERSION: 0.11.1
    image: vault-consul-client:node-2
    container_name: vault-client-2
    cap_add:
      - IPC_LOCK
    networks:
      default:
        aliases:
          - vault-client-1
        ipv4_address: 192.168.4.7
    volumes:
      - "./configs/consul-client/consul-agent-node-2.json:/consul/config/server.json:ro"
      - "./configs/consul-client/vault-config-node-2.hcl:/vault/config/config.hcl:ro"

  vault-client-3:
    build:
      context: ./client-srv
      args:
        CONSUL_VERSION: 1.2.2
        VAULT_VERSION: 0.11.1
    image: vault-consul-client:node-3
    container_name: vault-client-3
    cap_add:
      - IPC_LOCK
    networks:
      default:
        aliases:
          - vault-client-3
        ipv4_address: 192.168.4.8
    volumes:
      - "./configs/consul-client/consul-agent-node-3.json:/consul/config/server.json:ro"
      - "./configs/consul-client/vault-config-node-3.hcl:/vault/config/config.hcl:ro"

  web-bln-1:
    image: nginx:1.14.0
    container_name: web-bln-1
    networks:
      default:
        aliases:
          - web-bln-1
        ipv4_address: 192.168.4.5
    volumes:
      - "./configs/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./configs/nginx/certs:/etc/nginx/certs:ro"
      - "./configs/nginx/includes.d:/etc/nginx/includes.d:ro"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.4.0/26
